export const FUND_TYPES = [
  {
    value: "chama",
    label: "Chama",
    description: "Recurring, members-only table banking with an ongoing balance.",
    icon: "\u{1F91D}",
    image: "/images/chama.jpg",
    goalBased: false,
    publicOptional: false,
    fastTracked: false,
  },
  {
    value: "emergency",
    label: "Emergency Fund",
    description: "Recurring, members-only reserve for urgent needs.",
    icon: "\u{1F6A8}",
    image: "/images/emergency.jpg",
    goalBased: false,
    publicOptional: false,
    fastTracked: true,
  },
  {
    value: "matanga",
    label: "Matanga",
    description: "Funeral contribution fund with fast-tracked claim approval.",
    icon: "\u{1F54A}️",
    image: "/images/matanga.jpg",
    goalBased: false,
    publicOptional: false,
    fastTracked: true,
  },
  {
    value: "wedding",
    label: "Wedding",
    description: "Goal-based fund with an optional public contribution link.",
    icon: "\u{1F48D}",
    image: "/images/wedding.jpg",
    goalBased: true,
    publicOptional: true,
    fastTracked: false,
  },
  {
    value: "trip",
    label: "Trip",
    description: "Goal-based, members-only savings for a group trip.",
    icon: "✈️",
    image: "/images/trip.jpg",
    goalBased: true,
    publicOptional: false,
    fastTracked: false,
  },
  {
    value: "harambee",
    label: "Harambee",
    description: "Goal-based public fundraiser — no login required to contribute.",
    icon: "\u{1F3E0}",
    image: "/images/harambee.jpg",
    goalBased: true,
    publicOptional: false,
    forcePublic: true,
    fastTracked: false,
  },
];

export const fundTypeMeta = (value) => FUND_TYPES.find((f) => f.value === value) || FUND_TYPES[0];
